export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_IMAGES_GALLERY = 'UPDATE_IMAGES_GALLERY';

// Auth
export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';